development:
  adapter: async

test:
  adapter: async

staging:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: pd-aux-training_staging

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: pd-aux-training_production
